/* generated by Svelte v3.38.3 */
import { SvelteComponent, init, safe_not_equal } from '../web_modules/svelte/internal/index.mjs';

const completeUser = username => username.length > 0;
const completePass = password => password.length >= 6;
const passMatch = (password, confirmPass) => password === confirmPass;
const validEmail = email => (/\S+@\S+.\S+/).test(email); // Double backslashes.

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { completeUser, completePass, passMatch, validEmail };