/* generated by Svelte v3.38.3 */
import { SvelteComponent, init, safe_not_equal } from '../web_modules/svelte/internal/index.mjs';

import { writable } from '../web_modules/svelte/store/index.mjs';
const userbaseStore = writable(null);
const userStore = writable(null);
const authPromiseStore = writable(null);

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { userbaseStore, userStore, authPromiseStore };