/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div8;
	let div1;
	let div0;
	let t0;
	let t1;
	let ul0;
	let li0;
	let a0;
	let t2;
	let t3;
	let li1;
	let a1;
	let t4;
	let t5;
	let li2;
	let a2;
	let t6;
	let t7;
	let div3;
	let div2;
	let t8;
	let t9;
	let ul1;
	let li3;
	let a3;
	let t10;
	let t11;
	let li4;
	let a4;
	let t12;
	let t13;
	let li5;
	let a5;
	let t14;
	let t15;
	let div5;
	let div4;
	let t16;
	let t17;
	let ul2;
	let li6;
	let a6;
	let t18;
	let t19;
	let li7;
	let a7;
	let t20;
	let t21;
	let div7;
	let div6;
	let t22;
	let t23;
	let ul3;
	let li8;
	let a8;
	let t24;
	let t25;
	let li9;
	let a9;
	let t26;
	let t27;
	let li10;
	let a10;
	let t28;

	return {
		c() {
			section = element("section");
			div8 = element("div");
			div1 = element("div");
			div0 = element("div");
			t0 = text("Company");
			t1 = space();
			ul0 = element("ul");
			li0 = element("li");
			a0 = element("a");
			t2 = text("about");
			t3 = space();
			li1 = element("li");
			a1 = element("a");
			t4 = text("contact");
			t5 = space();
			li2 = element("li");
			a2 = element("a");
			t6 = text("pricing");
			t7 = space();
			div3 = element("div");
			div2 = element("div");
			t8 = text("Members");
			t9 = space();
			ul1 = element("ul");
			li3 = element("li");
			a3 = element("a");
			t10 = text("support");
			t11 = space();
			li4 = element("li");
			a4 = element("a");
			t12 = text("sign in");
			t13 = space();
			li5 = element("li");
			a5 = element("a");
			t14 = text("register");
			t15 = space();
			div5 = element("div");
			div4 = element("div");
			t16 = text("Projects");
			t17 = space();
			ul2 = element("ul");
			li6 = element("li");
			a6 = element("a");
			t18 = text("userbase");
			t19 = space();
			li7 = element("li");
			a7 = element("a");
			t20 = text("plentico");
			t21 = space();
			div7 = element("div");
			div6 = element("div");
			t22 = text("Resources");
			t23 = space();
			ul3 = element("ul");
			li8 = element("li");
			a8 = element("a");
			t24 = text("repo");
			t25 = space();
			li9 = element("li");
			a9 = element("a");
			t26 = text("theme");
			t27 = space();
			li10 = element("li");
			a10 = element("a");
			t28 = text("attribution");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { class: true });
			var section_nodes = children(section);
			div8 = claim_element(section_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);
			div1 = claim_element(div8_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			div0 = claim_element(div1_nodes, "DIV", { class: true });
			var div0_nodes = children(div0);
			t0 = claim_text(div0_nodes, "Company");
			div0_nodes.forEach(detach);
			t1 = claim_space(div1_nodes);
			ul0 = claim_element(div1_nodes, "UL", { class: true });
			var ul0_nodes = children(ul0);
			li0 = claim_element(ul0_nodes, "LI", { class: true });
			var li0_nodes = children(li0);
			a0 = claim_element(li0_nodes, "A", { href: true, class: true });
			var a0_nodes = children(a0);
			t2 = claim_text(a0_nodes, "about");
			a0_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t3 = claim_space(ul0_nodes);
			li1 = claim_element(ul0_nodes, "LI", { class: true });
			var li1_nodes = children(li1);
			a1 = claim_element(li1_nodes, "A", { href: true, class: true });
			var a1_nodes = children(a1);
			t4 = claim_text(a1_nodes, "contact");
			a1_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t5 = claim_space(ul0_nodes);
			li2 = claim_element(ul0_nodes, "LI", { class: true });
			var li2_nodes = children(li2);
			a2 = claim_element(li2_nodes, "A", { href: true, class: true });
			var a2_nodes = children(a2);
			t6 = claim_text(a2_nodes, "pricing");
			a2_nodes.forEach(detach);
			li2_nodes.forEach(detach);
			ul0_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t7 = claim_space(div8_nodes);
			div3 = claim_element(div8_nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			div2 = claim_element(div3_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			t8 = claim_text(div2_nodes, "Members");
			div2_nodes.forEach(detach);
			t9 = claim_space(div3_nodes);
			ul1 = claim_element(div3_nodes, "UL", { class: true });
			var ul1_nodes = children(ul1);
			li3 = claim_element(ul1_nodes, "LI", { class: true });
			var li3_nodes = children(li3);
			a3 = claim_element(li3_nodes, "A", { href: true, class: true });
			var a3_nodes = children(a3);
			t10 = claim_text(a3_nodes, "support");
			a3_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			t11 = claim_space(ul1_nodes);
			li4 = claim_element(ul1_nodes, "LI", { class: true });
			var li4_nodes = children(li4);
			a4 = claim_element(li4_nodes, "A", { href: true, class: true });
			var a4_nodes = children(a4);
			t12 = claim_text(a4_nodes, "sign in");
			a4_nodes.forEach(detach);
			li4_nodes.forEach(detach);
			t13 = claim_space(ul1_nodes);
			li5 = claim_element(ul1_nodes, "LI", { class: true });
			var li5_nodes = children(li5);
			a5 = claim_element(li5_nodes, "A", { href: true, class: true });
			var a5_nodes = children(a5);
			t14 = claim_text(a5_nodes, "register");
			a5_nodes.forEach(detach);
			li5_nodes.forEach(detach);
			ul1_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t15 = claim_space(div8_nodes);
			div5 = claim_element(div8_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			t16 = claim_text(div4_nodes, "Projects");
			div4_nodes.forEach(detach);
			t17 = claim_space(div5_nodes);
			ul2 = claim_element(div5_nodes, "UL", { class: true });
			var ul2_nodes = children(ul2);
			li6 = claim_element(ul2_nodes, "LI", { class: true });
			var li6_nodes = children(li6);

			a6 = claim_element(li6_nodes, "A", {
				href: true,
				target: true,
				rel: true,
				class: true
			});

			var a6_nodes = children(a6);
			t18 = claim_text(a6_nodes, "userbase");
			a6_nodes.forEach(detach);
			li6_nodes.forEach(detach);
			t19 = claim_space(ul2_nodes);
			li7 = claim_element(ul2_nodes, "LI", { class: true });
			var li7_nodes = children(li7);

			a7 = claim_element(li7_nodes, "A", {
				href: true,
				target: true,
				rel: true,
				class: true
			});

			var a7_nodes = children(a7);
			t20 = claim_text(a7_nodes, "plentico");
			a7_nodes.forEach(detach);
			li7_nodes.forEach(detach);
			ul2_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			t21 = claim_space(div8_nodes);
			div7 = claim_element(div8_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			div6 = claim_element(div7_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			t22 = claim_text(div6_nodes, "Resources");
			div6_nodes.forEach(detach);
			t23 = claim_space(div7_nodes);
			ul3 = claim_element(div7_nodes, "UL", { class: true });
			var ul3_nodes = children(ul3);
			li8 = claim_element(ul3_nodes, "LI", { class: true });
			var li8_nodes = children(li8);

			a8 = claim_element(li8_nodes, "A", {
				href: true,
				target: true,
				rel: true,
				class: true
			});

			var a8_nodes = children(a8);
			t24 = claim_text(a8_nodes, "repo");
			a8_nodes.forEach(detach);
			li8_nodes.forEach(detach);
			t25 = claim_space(ul3_nodes);
			li9 = claim_element(ul3_nodes, "LI", { class: true });
			var li9_nodes = children(li9);

			a9 = claim_element(li9_nodes, "A", {
				href: true,
				target: true,
				rel: true,
				class: true
			});

			var a9_nodes = children(a9);
			t26 = claim_text(a9_nodes, "theme");
			a9_nodes.forEach(detach);
			li9_nodes.forEach(detach);
			t27 = claim_space(ul3_nodes);
			li10 = claim_element(ul3_nodes, "LI", { class: true });
			var li10_nodes = children(li10);
			a10 = claim_element(li10_nodes, "A", { href: true, class: true });
			var a10_nodes = children(a10);
			t28 = claim_text(a10_nodes, "attribution");
			a10_nodes.forEach(detach);
			li10_nodes.forEach(detach);
			ul3_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			div8_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "label svelte-1b0s0c7");
			attr(a0, "href", "/about");
			attr(a0, "class", "svelte-1b0s0c7");
			attr(li0, "class", "svelte-1b0s0c7");
			attr(a1, "href", "/contact");
			attr(a1, "class", "svelte-1b0s0c7");
			attr(li1, "class", "svelte-1b0s0c7");
			attr(a2, "href", "/pricing");
			attr(a2, "class", "svelte-1b0s0c7");
			attr(li2, "class", "svelte-1b0s0c7");
			attr(ul0, "class", "svelte-1b0s0c7");
			attr(div1, "class", "column svelte-1b0s0c7");
			attr(div2, "class", "label svelte-1b0s0c7");
			attr(a3, "href", "/contact");
			attr(a3, "class", "svelte-1b0s0c7");
			attr(li3, "class", "svelte-1b0s0c7");
			attr(a4, "href", "/user");
			attr(a4, "class", "svelte-1b0s0c7");
			attr(li4, "class", "svelte-1b0s0c7");
			attr(a5, "href", "/user/register");
			attr(a5, "class", "svelte-1b0s0c7");
			attr(li5, "class", "svelte-1b0s0c7");
			attr(ul1, "class", "svelte-1b0s0c7");
			attr(div3, "class", "column svelte-1b0s0c7");
			attr(div4, "class", "label svelte-1b0s0c7");
			attr(a6, "href", "https://userbase.com");
			attr(a6, "target", "blank");
			attr(a6, "rel", "noopener noreferrer");
			attr(a6, "class", "svelte-1b0s0c7");
			attr(li6, "class", "svelte-1b0s0c7");
			attr(a7, "href", "https://plenti.co");
			attr(a7, "target", "blank");
			attr(a7, "rel", "noopener noreferrer");
			attr(a7, "class", "svelte-1b0s0c7");
			attr(li7, "class", "svelte-1b0s0c7");
			attr(ul2, "class", "svelte-1b0s0c7");
			attr(div5, "class", "column svelte-1b0s0c7");
			attr(div6, "class", "label svelte-1b0s0c7");
			attr(a8, "href", "https://github.com/plenti-themes/userbase");
			attr(a8, "target", "blank");
			attr(a8, "rel", "noopener noreferrer");
			attr(a8, "class", "svelte-1b0s0c7");
			attr(li8, "class", "svelte-1b0s0c7");
			attr(a9, "href", "https://plenti.co/themes/userbase");
			attr(a9, "target", "blank");
			attr(a9, "rel", "noopener noreferrer");
			attr(a9, "class", "svelte-1b0s0c7");
			attr(li9, "class", "svelte-1b0s0c7");
			attr(a10, "href", "/attribution");
			attr(a10, "class", "svelte-1b0s0c7");
			attr(li10, "class", "svelte-1b0s0c7");
			attr(ul3, "class", "svelte-1b0s0c7");
			attr(div7, "class", "column svelte-1b0s0c7");
			attr(div8, "class", "container svelte-1b0s0c7");
			attr(section, "class", "svelte-1b0s0c7");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div8);
			append(div8, div1);
			append(div1, div0);
			append(div0, t0);
			append(div1, t1);
			append(div1, ul0);
			append(ul0, li0);
			append(li0, a0);
			append(a0, t2);
			append(ul0, t3);
			append(ul0, li1);
			append(li1, a1);
			append(a1, t4);
			append(ul0, t5);
			append(ul0, li2);
			append(li2, a2);
			append(a2, t6);
			append(div8, t7);
			append(div8, div3);
			append(div3, div2);
			append(div2, t8);
			append(div3, t9);
			append(div3, ul1);
			append(ul1, li3);
			append(li3, a3);
			append(a3, t10);
			append(ul1, t11);
			append(ul1, li4);
			append(li4, a4);
			append(a4, t12);
			append(ul1, t13);
			append(ul1, li5);
			append(li5, a5);
			append(a5, t14);
			append(div8, t15);
			append(div8, div5);
			append(div5, div4);
			append(div4, t16);
			append(div5, t17);
			append(div5, ul2);
			append(ul2, li6);
			append(li6, a6);
			append(a6, t18);
			append(ul2, t19);
			append(ul2, li7);
			append(li7, a7);
			append(a7, t20);
			append(div8, t21);
			append(div8, div7);
			append(div7, div6);
			append(div6, t22);
			append(div7, t23);
			append(div7, ul3);
			append(ul3, li8);
			append(li8, a8);
			append(a8, t24);
			append(ul3, t25);
			append(ul3, li9);
			append(li9, a9);
			append(a9, t26);
			append(ul3, t27);
			append(ul3, li10);
			append(li10, a10);
			append(a10, t28);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;