/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	assign,
	attr,
	check_outros,
	children,
	claim_component,
	claim_element,
	claim_space,
	create_component,
	destroy_component,
	detach,
	element,
	get_spread_object,
	get_spread_update,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from '../web_modules/svelte/internal/index.mjs';

import Head from './head.js';
import Nav from './nav.js';
import Footer from './footer.js';
import { onMount } from '../web_modules/svelte/index.mjs';
import { userStore } from '../scripts/stores.js';
import { userbaseStore } from '../scripts/stores.js';
import { authPromiseStore } from '../scripts/stores.js';

function create_fragment(ctx) {
	let html;
	let head;
	let t0;
	let body;
	let nav;
	let t1;
	let div;
	let switch_instance;
	let t2;
	let footer;
	let current;

	head = new Head({
			props: { title: /*content*/ ctx[0].filename }
		});

	nav = new Nav({});
	const switch_instance_spread_levels = [/*content*/ ctx[0].fields];
	var switch_value = /*layout*/ ctx[1];

	function switch_props(ctx) {
		let switch_instance_props = {};

		for (let i = 0; i < switch_instance_spread_levels.length; i += 1) {
			switch_instance_props = assign(switch_instance_props, switch_instance_spread_levels[i]);
		}

		return { props: switch_instance_props };
	}

	if (switch_value) {
		switch_instance = new switch_value(switch_props(ctx));
	}

	footer = new Footer({});

	return {
		c() {
			html = element("html");
			create_component(head.$$.fragment);
			t0 = space();
			body = element("body");
			create_component(nav.$$.fragment);
			t1 = space();
			div = element("div");
			if (switch_instance) create_component(switch_instance.$$.fragment);
			t2 = space();
			create_component(footer.$$.fragment);
			this.h();
		},
		l(nodes) {
			html = claim_element(nodes, "HTML", { lang: true });
			var html_nodes = children(html);
			claim_component(head.$$.fragment, html_nodes);
			t0 = claim_space(html_nodes);
			body = claim_element(html_nodes, "BODY", { class: true });
			var body_nodes = children(body);
			claim_component(nav.$$.fragment, body_nodes);
			t1 = claim_space(body_nodes);
			div = claim_element(body_nodes, "DIV", { class: true });
			var div_nodes = children(div);
			if (switch_instance) claim_component(switch_instance.$$.fragment, div_nodes);
			div_nodes.forEach(detach);
			t2 = claim_space(body_nodes);
			claim_component(footer.$$.fragment, body_nodes);
			body_nodes.forEach(detach);
			html_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div, "class", "container");
			attr(body, "class", "svelte-820cvn");
			attr(html, "lang", "en");
		},
		m(target, anchor) {
			insert(target, html, anchor);
			mount_component(head, html, null);
			append(html, t0);
			append(html, body);
			mount_component(nav, body, null);
			append(body, t1);
			append(body, div);

			if (switch_instance) {
				mount_component(switch_instance, div, null);
			}

			append(body, t2);
			mount_component(footer, body, null);
			current = true;
		},
		p(ctx, [dirty]) {
			const head_changes = {};
			if (dirty & /*content*/ 1) head_changes.title = /*content*/ ctx[0].filename;
			head.$set(head_changes);

			const switch_instance_changes = (dirty & /*content*/ 1)
			? get_spread_update(switch_instance_spread_levels, [get_spread_object(/*content*/ ctx[0].fields)])
			: {};

			if (switch_value !== (switch_value = /*layout*/ ctx[1])) {
				if (switch_instance) {
					group_outros();
					const old_component = switch_instance;

					transition_out(old_component.$$.fragment, 1, 0, () => {
						destroy_component(old_component, 1);
					});

					check_outros();
				}

				if (switch_value) {
					switch_instance = new switch_value(switch_props(ctx));
					create_component(switch_instance.$$.fragment);
					transition_in(switch_instance.$$.fragment, 1);
					mount_component(switch_instance, div, null);
				} else {
					switch_instance = null;
				}
			} else if (switch_value) {
				switch_instance.$set(switch_instance_changes);
			}
		},
		i(local) {
			if (current) return;
			transition_in(head.$$.fragment, local);
			transition_in(nav.$$.fragment, local);
			if (switch_instance) transition_in(switch_instance.$$.fragment, local);
			transition_in(footer.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(head.$$.fragment, local);
			transition_out(nav.$$.fragment, local);
			if (switch_instance) transition_out(switch_instance.$$.fragment, local);
			transition_out(footer.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(html);
			destroy_component(head);
			destroy_component(nav);
			if (switch_instance) destroy_component(switch_instance);
			destroy_component(footer);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	onMount(async () => {
		userbaseStore.set(window.userbase);

		userbaseStore.subscribe(userbase => {
			let authPromise = userbase.init({
				appId: "a986a20c-7654-4c44-9e5e-1ea0b57803d9",
				allowServerSideEncryption: true
			}).then(({ user }) => userStore.set(user));

			authPromiseStore.set(authPromise);
		});
	});

	let { content } = $$props, { layout } = $$props;

	$$self.$$set = $$props => {
		if ("content" in $$props) $$invalidate(0, content = $$props.content);
		if ("layout" in $$props) $$invalidate(1, layout = $$props.layout);
	};

	return [content, layout];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { content: 0, layout: 1 });
	}
}

export default Component;